<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>BennysMotorworksRevamped</RootNamespace>
    <AssemblyName>BennysMotorworksRevamped</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageProjectUrl>https://github.com/Nochala/BennysMotorworksRevamped</PackageProjectUrl>
    <Authors>Nochala</Authors>
    <Title>BennysMotorworksRevamped</Title>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>low</NuGetAuditLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="LemonUI.SHVDN3">
      <HintPath>..\LemonUI\LemonUI.SHVDN3.dll</HintPath>
    </Reference>
    <Reference Include="ScriptHookVDotNet3">
      <HintPath>..\ScriptHookVDotNet3.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
